### ISSUE TITLE
Example code bug in README

### ISSUE THREAD

**Issue by KDahlgren** [ashutoshraina/slug#2]
"dot -Tpng samples/input.dot > output.png" doesn't work. No input.dot created after build. Need to cd into one of the generated samples/ directories and pick a dot file to visualize.

**Comment by ashutoshraina** [comment]
I have changed the instructions to make this a lot clearer. Please try again, and let me know if further modification is required.

**Comment by ashutoshraina** [comment]
I have modified the readme to be much clearer and bulleted to increase readability.
